export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECT_RESPONSE = "LOAD_PROJECT_RESPONSE";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const GET_USERS_RESPONSE = "GET_USERS_RESPONSE";
export const SAVE_PROJECT_RESPONSE = "SAVE_PROJECT_RESPONSE";
