export const CREATE_PROJECT = "CREATE_PROJECT";
export const LOAD_PROJECT_RESPONSE = "LOAD_PROJECT_RESPONSE";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const LOAD_USER_RESPONSE = "LOAD_USER_RESPONSE";
